# Generated by Django 4.2.4 on 2023-12-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('originalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ratedPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('contactInfo', models.CharField(max_length=255)),
                ('warranty', models.CharField(max_length=255)),
                ('guarantee', models.CharField(max_length=255)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='second_product_photos/')),
            ],
        ),
    ]
