# Generated by Django 4.2.4 on 2023-12-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecondHand', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='SecondProduct',
        ),
    ]
