# Generated by Django 4.2.4 on 2023-12-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecondHand', '0002_rename_product_secondproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondproduct',
            name='photos',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='second_product_photos/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='SecondHand.secondproduct')),
            ],
        ),
    ]
