# Generated by Django 4.2.4 on 2023-12-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondHand', '0003_remove_secondproduct_photos_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondproduct',
            name='guarantee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='secondproduct',
            name='warranty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
