# Generated by Django 4.2.4 on 2023-12-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecondHand', '0004_alter_secondproduct_guarantee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
        migrations.AddField(
            model_name='secondproduct',
            name='images',
            field=models.ManyToManyField(to='SecondHand.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]
