# Generated by Django 4.2.4 on 2023-12-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SecondHand', '0006_alter_image_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='second_product_photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='secondproduct',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='secondproductimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondproductimage_set', to='SecondHand.secondproduct'),
        ),
    ]
