# Generated by Django 4.2.4 on 2023-10-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_seller_rename_name_product_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='regular_price',
        ),
    ]
