# Generated by Django 4.2.4 on 2023-10-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products_images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
