# Generated by Django 4.2.4 on 2023-12-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_product_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
