# Generated by Django 4.2.4 on 2023-12-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0020_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isFlashSale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='isNewArrival',
            field=models.BooleanField(default=False),
        ),
    ]
