# Generated by Django 4.2.4 on 2023-11-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseHistory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorderhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
