# Generated by Django 4.2.4 on 2023-11-30 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_remove_seller_user'),
        ('PurchaseHistory', '0002_alter_sellerorderhistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorderhistory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.seller'),
        ),
    ]
