# Generated by Django 4.2.4 on 2023-11-30 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PurchaseHistory', '0003_alter_sellerorderhistory_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorderhistory',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
