# Generated by Django 4.2.4 on 2023-11-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseHistory', '0004_alter_sellerorderhistory_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerOrderHistory',
        ),
    ]
