# Generated by Django 4.2.4 on 2023-11-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseHistory', '0006_sellerorderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerorderhistory',
            name='customers_emails',
            field=models.JSONField(default=list),
        ),
    ]
