# Generated by Django 4.2.4 on 2023-11-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseHistory', '0007_sellerorderhistory_customers_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerorderhistory',
            name='customers_emails',
        ),
    ]
