# Generated by Django 4.2.4 on 2023-11-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseHistory', '0008_remove_sellerorderhistory_customers_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerorderhistory',
            name='customers_emails',
            field=models.JSONField(default=list),
        ),
    ]
