# Generated by Django 4.2.4 on 2023-12-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseHistory', '0010_purchasehistory_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_sales', models.PositiveIntegerField(default=0)),
                ('seller_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PurchaseHistory.sellerorderhistory')),
            ],
        ),
    ]
