# Generated by Django 4.2.4 on 2023-09-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_rename_fullname_customuser_fusallname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fusallName',
            new_name='fullName',
        ),
    ]
