# Generated by Django 4.2.4 on 2023-10-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_images'),
        ),
    ]
