# Generated by Django 4.2.4 on 2023-12-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0017_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='addresss',
        ),
    ]
