# Generated by Django 4.2.4 on 2023-12-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_rename_address_address_addresss'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seller_status',
            field=models.BooleanField(default=False),
        ),
    ]
