# Generated by Django 4.2.4 on 2023-12-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0020_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pan',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
